services:
  app:
    container_name: hexagone_six
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    volumes:
      - storage:/app/storage

volumes:
  storage:
