name: Discord Notification

on:
  push:
    branches:
      - '*'

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit details
        id: commit-details
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_SHA=$(git log -1 --pretty=format:"%h")
          COMMIT_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/$(git log -1 --pretty=format:"%H")"
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "author=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
          echo "sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "commit_url=$COMMIT_URL" >> $GITHUB_OUTPUT

      - name: Send Discord Notification
        run: |
          cat > payload.json << EOF
          {
            "username": "GitHub",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [
              {
                "title": "${{ github.repository }} - ${{ github.ref_name }}",
                "url": "${{ steps.commit-details.outputs.commit_url }}",
                "color": 5814783,
                "fields": [
                  {
                    "name": "Details du commit",
                    "value": "${{ steps.commit-details.outputs.message }}"
                  }
                ],
                "author": {
                  "name": "${{ steps.commit-details.outputs.author }}"
                },
                "footer": {
                  "text": "${{ github.event.repository.name }}"
                },
                "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
              }
            ]
          }
          EOF
          curl -H "Content-Type: application/json" -X POST ${{ secrets.DISCORD_WEBHOOK }} -d @payload.json
