name: Discord Notification - Development Branch

on:
  push:
    branches:
      - 'develop' # Uniquement sur la branche develop

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit details
        id: commit-details
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_SHA=$(git log -1 --pretty=format:"%h")
          COMMIT_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/$(git log -1 --pretty=format:"%H")"
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "author=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
          echo "sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "commit_url=$COMMIT_URL" >> $GITHUB_OUTPUT

      - name: Send Discord Notification
        env:
          REPO: ${{ github.repository }}
          BRANCH: ${{ steps.commit-details.outputs.branch }}
          COMMIT_URL: ${{ steps.commit-details.outputs.commit_url }}
          COMMIT_SHA: ${{ steps.commit-details.outputs.sha }}
          COMMIT_MSG: ${{ steps.commit-details.outputs.message }}
          AUTHOR: ${{ steps.commit-details.outputs.author }}
        run: |
          COMMIT_MSG_ESCAPED=$(echo "$COMMIT_MSG" | jq -Rs .)
          AUTHOR_ESCAPED=$(echo "$AUTHOR" | jq -Rs .)

          jq -n \
          --arg repo "$REPO" \
          --arg branch "$BRANCH" \
          --arg commit_url "$COMMIT_URL" \
          --arg commit_sha "$COMMIT_SHA" \
          --argjson commit_msg $COMMIT_MSG_ESCAPED \
          --argjson author $AUTHOR_ESCAPED \
          --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
          '{
            "username": "GitHub",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [
              {
                "title": $repo + " - " + $branch,
                "url": $commit_url,
                "color": 5814783,
                "fields": [
                  {
                    "name": "Commit",
                    "value": "[" + $commit_sha + "](" + $commit_url + ")",
                    "inline": true
                  },
                  {
                    "name": "Message",
                    "value": $commit_msg
                  }
                ],
                "footer": {
                  "text": "Par " + $author
                },
                "timestamp": $timestamp
              }
            ]
          }' > payload.json

          curl -H "Content-Type: application/json" -X POST ${{ secrets.DISCORD_WEBHOOK }} -d @payload.json
