name: Discord Notification - Development Branch

on:
  push:
    branches:
      - 'develop' # Only trigger on pushes to the 'develop' branch

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to get commit details

      - name: Get commit details
        id: commit-details
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_SHA=$(git log -1 --pretty=format:"%h")
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "author=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
          echo "sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Send Discord Message
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            **New commit pushed to `${{ steps.commit-details.outputs.branch }}`**
            **Author:** ${{ steps.commit-details.outputs.author }}
            **Commit:** ${{ steps.commit-details.outputs.sha }}
            **Message:** ${{ steps.commit-details.outputs.message }}
            **Repository:** ${{ github.repository }}
